apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-deployment
spec:
  selector:
    matchLabels:
      app: api-label
  template:
    metadata:
      labels:
        app: api-label
    spec:
      containers:
      - name: api
        image: fredericeducentre/facturation-api:v1
---
kind: Service
apiVersion: v1
metadata:
  name: api-service
spec:
  selector:
    app: api-label
  type: NodePort
  ports:
    - port: 3000
