
apiVersion: v1
kind: Service
metadata:
  name: front
  labels:
    app: front
spec:
  ports:
    - port: 80
  selector:
    app: front
    tier: frontend
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: front
  labels:
    app: front
spec:
  selector:
    matchLabels:
      app: front
      tier: frontend
  template:
    metadata:
      labels:
        app: front
        tier: frontend
    spec:
      containers:
      - image: fredericeducentre/facture-front
        name: front
        